dictionaries = ["en_gb"]
words = [
    "Peeker",
    "Werror",
    "Xlint",
    "aosp",
    "diffplug",
    "errorprone",
    "jspecify",
    "ltgt",
    "nullaway",
    "palantir",
    "peekable",
    "reflow",
    "sool",
    "tokenise",
    "traverser",
    "uber",
]
ignore_paths = [
    "LICENSE",
    "config/checkstyle/*",
]
use_global = false
